import { IdAndName } from "@/models/IdAndNameDto";
import { FormInput } from "../shared/form/FormInput";
import { FormSelect } from "../shared/form/FormSelect";

const brands: string[] = [
  "Abarth",
  "Acura",
  "Aixam",
  "Alfa Romeo",
  "Alpine",
  "Aro",
  "Asia",
  "Aston Martin",
  "Audi",
  "Austin",
  "Autobianchi",
  "Baic",
  "Befard",
  "Bentley",
  "BMW",
  "Bobcat",
  "Bolloré",
  "Brilliance",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Casalini",
  "Caterham",
  "Chatenet",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Comarth",
  "Cupra",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "De Lorean",
  "DFSK",
  "DKW",
  "Dodge",
  "DS Automobiles",
  "Eagle",
  "FAW",
  "Ferrari",
  "Fiat",
  "Ford",
  "Galloper",
  "Gaspardo",
  "Gaz",
  "Geely",
  "GMC",
  "Gonow",
  "Grecav",
  "GWM",
  "Hammer",
  "Holden",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Iveco",
  "Jaguar",
  "Jeep",
  "John Deere",
  "Kaipan",
  "Kia",
  "Kuhn",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Ligier",
  "Lincoln",
  "Lotus",
  "LTI",
  "LuAZ",
  "Mahindra",
  "Maruti",
  "Maserati",
  "Maybach",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mercury",
  "MG",
  "Microcar",
  "Mini",
  "Mitsubishi",
  "Morgan",
  "Moskwicz",
  "Nissan",
  "NSU",
  "Nysa",
  "Oldsmobile",
  "Oltcit",
  "Opel",
  "Peugeot",
  "Piaggio",
  "Plymouth",
  "Polonez",
  "Pontiac",
  "Porsche",
  "Proton",
  "RAM",
  "Rayton Fissore",
  "Renault",
  "Rolls-Royce",
  "Rover",
  "Saab",
  "Santana",
  "Saturn",
  "Scion",
  "Seat",
  "Shuanghuan",
  "Škoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Syrena",
  "Talbot",
  "Tarpan",
  "Tata",
  "Tatra",
  "Tavria",
  "Tesla",
  "Thumm",
  "Toyota",
  "Trabant",
  "Triumph",
  "TVR",
  "Uaz",
  "Vauxhall",
  "Volkswagen",
  "Volvo",
  "VTN",
  "Warszawa",
  "Wartburg",
  "Weismann",
  "Wołga",
  "Yugo",
  "Zaporożec",
  "Zastava",
  "Żuk",
  "Inny",
];

export const AdvancedSearchBar = () => {
  return (
    <form className="border-1 border-regal-blue-light/20 rounded-lg p-4 flex flex-wrap justify-between content-start">
      <FormSelect
        id="brand"
        label="Brand"
        placeholder="Select car brand(s)"
        options={brands}
      />
      <FormInput id="brand" label="Brand" placeholder="" />
      <FormInput id="model" label="Model" placeholder="" />
      <FormInput id="version" label="Version" placeholder="" />
    </form>
  );
};
